### ISSUE TITLE
How to delete any data via "Any Request"

### ISSUE THREAD

**Issue by lukaszpitulski** [TravisTX/elasticsearch-head-chrome#10]
in "Any Request" tab in "Query" section:
query's body: {"query":{"bool":{"must":[{"prefix":{"id.keyword":"123"}}]}}} 
path: _search 
method: POST 

How to delete from ES the data which are in the result of the query/request above?

**Comment by krzotr** [comment]
To remove documents from Elasticsearch by query you have to use `_delete_by_query`

Your path is incorrect. Instead of `_search` use `_delete_by_query`. Please see [_delete_by_query Api Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) for more details.

**Comment by lukaszpitulski** [comment]
and use Index and Type in the query
